<a href="https://colab.research.google.com/github/NMThanh123/Exercies_AI/blob/main/AI_W8(24_03_2023).ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

                                                            Artifical Neural Netwwork

In [ ]:
from sklearn.linear_model import Perceptron
import numpy as np
X = [[0, 0], [11, 0], [0, 1], [1, 1]]
y = [0, 1, 1, 1]
x1 = [[0.5, 0], [0, 0.5], [0.6, 0], [0, 0.6], [-10, 2], [0.1, 1], [-0.3, 4]]
model = Perceptron()
model.fit(X, y)
model.score(X, y)

y1 = model.predict(x1)
print(y1)

[0 0 0 1 0 1 1]


In [ ]:
from sklearn.linear_model import Perceptron
import numpy as np
X = [[-0.5, -0.5], [-0.5, 0.5], [0.3, -0.5], [-0.1, 1]]
y = [1, 1, 0, 0]

x1 = [[0.5, 0], [0, 0.5], [0.6, 0], [0, 0.6], [-10, 2], [0.1, 1], [-0.3, 4]]

model = Perceptron()
model.fit(X, y)
model.score(X, y)

y1 = model.predict(x1)
print(y1)

[0 0 0 0 1 0 0]


In [ ]:
from sklearn import datasets as dt
from sklearn.linear_model import Perceptron
from sklearn.model_selection import train_test_split
from sklearn.metrics import accuracy_score
from sklearn.preprocessing import StandardScaler

data = dt.load_iris()
df = data.data
target = data.target

X_train, X_test, y_train, y_test = train_test_split(df, target, test_size=0.2)

standard = StandardScaler()
X_train_sc = standard.fit_transform(X_train)
X_test_sc = standard.fit_transform(X_test)

model = Perceptron(max_iter=1000, eta0=0.1, random_state=0)
model.fit(X_train, y_train)
y_pred = model.predict(X_test)
print('độ chính xác khi chưa scale: ', accuracy_score(y_test, y_pred))

độ chính xác khi chưa scale:  0.7333333333333333


In [ ]:
model = Perceptron(max_iter=1000, eta0=0.1, random_state=0)
model.fit(X_train_sc, y_train)
y_pred = model.predict(X_test_sc)
print('độ chính xác khi chưa scale: ', accuracy_score(y_test, y_pred))

np.set_printoptions(precision=2)
print(np.concatenate((y_pred.reshape(len(y_pred), 1), y_test.reshape(len(y_test), 1)), axis=1))

độ chính xác khi chưa scale:  0.8666666666666667
[[0 1]
 [0 0]
 [2 2]
 [0 1]
 [0 0]
 [2 2]
 [2 2]
 [0 0]
 [2 2]
 [2 2]
 [0 0]
 [2 1]
 [1 0]
 [2 2]
 [2 2]
 [2 2]
 [0 0]
 [0 0]
 [0 0]
 [1 1]
 [2 2]
 [2 2]
 [0 0]
 [0 0]
 [1 1]
 [2 2]
 [0 0]
 [1 1]
 [2 2]
 [1 1]]


In [ ]:
import pandas as pd

In [ ]:
data = pd.read_csv('Data/crabs.csv')

In [ ]:
data

speies sex  index  fontallip  rearwidth  length  width  depth
0        B   M      1        8.1        6.7    16.1   19.0    7.0
1        B   M      2        8.8        7.7    18.1   20.8    7.4
2        B   M      3        9.2        7.8    19.0   22.4    7.7
3        B   M      4        9.6        7.9    20.1   23.1    8.2
4        B   M      5        9.8        8.0    20.3   23.0    8.2
..     ...  ..    ...        ...        ...     ...    ...    ...
195      O   F     46       21.4       18.0    41.2   46.2   18.7
196      O   F     47       21.7       17.1    41.7   47.2   19.6
197      O   F     48       21.9       17.2    42.6   47.4   19.5
198      O   F     49       22.5       17.2    43.0   48.7   19.8
199      O   F     50       23.1       20.2    46.2   52.5   21.1

[200 rows x 8 columns]

In [ ]:
speies = data['speies'].replace({'B':0, 'O':1})
sex = data['sex'].replace({'M':1, 'F':0})
data['speies'] = speies
data['sex'] = sex
data


speies  sex  index  fontallip  rearwidth  length  width  depth
0         0    1      1        8.1        6.7    16.1   19.0    7.0
1         0    1      2        8.8        7.7    18.1   20.8    7.4
2         0    1      3        9.2        7.8    19.0   22.4    7.7
3         0    1      4        9.6        7.9    20.1   23.1    8.2
4         0    1      5        9.8        8.0    20.3   23.0    8.2
..      ...  ...    ...        ...        ...     ...    ...    ...
195       1    0     46       21.4       18.0    41.2   46.2   18.7
196       1    0     47       21.7       17.1    41.7   47.2   19.6
197       1    0     48       21.9       17.2    42.6   47.4   19.5
198       1    0     49       22.5       17.2    43.0   48.7   19.8
199       1    0     50       23.1       20.2    46.2   52.5   21.1

[200 rows x 8 columns]

In [ ]:
from sklearn import datasets as dt
from sklearn.linear_model import Perceptron
from sklearn.model_selection import train_test_split
from sklearn.metrics import accuracy_score
from sklearn.preprocessing import StandardScaler
import numpy as np

X = data.iloc[:, 3:]
y = data.iloc[:,1]
X_train, X_test, y_train, y_test = train_test_split(X, y, test_size=0.2)

standard = StandardScaler()
X_train_sc = standard.fit_transform(X_train)
X_test_sc = standard.fit_transform(X_test)

model = Perceptron(max_iter=1000, eta0=0.1, random_state=0)
model.fit(X_train_sc, y_train)
y_pred = model.predict(X_test_sc)
print(y_pred)
print(np.array(y_test))
print('độ chính xác khi scale: ', accuracy_score(y_test, y_pred))

[1 1 1 1 1 1 1 0 1 1 0 0 0 0 0 0 1 1 0 1 1 0 1 0 1 1 1 1 0 0 1 1 0 0 0 1 1
 1 1 0]
[1 1 0 1 1 1 1 0 1 1 0 0 0 0 0 0 1 1 0 0 1 0 1 0 1 1 1 1 0 0 1 1 0 0 0 1 1
 1 1 0]
độ chính xác khi scale:  0.95


In [ ]:
data = pd.read_csv('Data/lung_cancer_examples.csv')
data = data.drop(columns=['Name', 'Surname'], axis=1)
data

Age  Smokes  AreaQ  Alkhol  Result
0    35       3      5       4       1
1    27      20      2       5       1
2    30       0      5       2       0
3    28       0      8       1       0
4    68       4      5       6       1
5    34       0     10       0       0
6    58      15     10       0       0
7    22      12      5       2       0
8    45       2      6       0       0
9    52      18      4       5       1
10   33       4      8       0       0
11   18      10      6       3       0
12   25       2      5       1       0
13   28      20      2       8       1
14   34      25      4       8       1
15   39      18      8       1       0
16   42      22      3       5       1
17   19      12      8       0       0
18   62       5      4       3       1
19   73      10      7       6       1
20   55      15      1       3       1
21   33       8      8       1       0
22   22      20      6       2       0
23   44       5      8       1       0
24   77       3      2       6       1
25   21      20      5       3       0
26   37      15      6       2       0
27   34      12      8       0       0
28   55      20      1       4       1
29   40      20      2       7       1
30   36      13      5       2       0
31   56      20      3       3       1
32   47      15      1       8       1
33   62      25      3       4       1
34   26      10      7       2       0
35   25      20      8       2       0
36   59      20      3       4       1
37   62      15      5       5       1
38   33      25      8       2       0
39   37      10      5       3       0
40   50      20      2       4       1
41   47      12      8       0       0
42   69      20      5       4       1
43   63      20      4       5       1
44   39      15      7       2       0
45   21      20      8       3       0
46   31      20      9       4       0
47   28      10      4       1       0
48   53      20      6       3       1
49   62      20      5       6       1
50   42      12      6       2       0
51   44      30      1       6       1
52   26      34      1       8       1
53   35      20      5       1       0
54   26      13      6       1       0
55   77      20      5       4       1
56   75      15      3       5       1
57   43      30      3       8       1
58   51      25      9       0       0

In [ ]:
from sklearn import datasets as dt
from sklearn.linear_model import Perceptron
from sklearn.model_selection import train_test_split
from sklearn.metrics import accuracy_score
from sklearn.preprocessing import StandardScaler
import numpy as np

X = data.iloc[:, 0:4]
y = data.iloc[:,-1]
X_train, X_test, y_train, y_test = train_test_split(X, y, test_size=0.2)

standard = StandardScaler()
X_train_sc = standard.fit_transform(X_train)
X_test_sc = standard.transform(X_test)

model = Perceptron(max_iter=100, eta0=0.7, random_state=0)
model.fit(X_train_sc, y_train)
y_pred = model.predict(X_test_sc)
x1 = np.array([[51, 20, 9, 6]])
x1 = standard.transform(x1)
s = model.predict(x1)
print(y_pred)
print(s)
print(np.array(y_test))
print('độ chính xác khi scale: ', accuracy_score(y_test, y_pred))

[0 1 0 0 0 0 1 0 1 1 0 1]
[1]
[0 1 0 0 0 0 1 0 1 1 0 1]
độ chính xác khi scale:  1.0


c:\Users\AsusTUF\anaconda3\lib\site-packages\sklearn\base.py:450: UserWarning: X does not have valid feature names, but StandardScaler was fitted with feature names
  warnings.warn(


In [ ]:
data = pd.read_csv('Data/pima-indians-diabetes.csv', header=None)
data = pd.DataFrame(np.array(data), columns=['2', '4', '6', '8', '9', '9', '6', '7', '5'])
df

2      4     6     8      9     9      6     7    5
0     6.0  148.0  72.0  35.0    0.0  33.6  0.627  50.0  1.0
1     1.0   85.0  66.0  29.0    0.0  26.6  0.351  31.0  0.0
2     8.0  183.0  64.0   0.0    0.0  23.3  0.672  32.0  1.0
3     1.0   89.0  66.0  23.0   94.0  28.1  0.167  21.0  0.0
4     0.0  137.0  40.0  35.0  168.0  43.1  2.288  33.0  1.0
..    ...    ...   ...   ...    ...   ...    ...   ...  ...
763  10.0  101.0  76.0  48.0  180.0  32.9  0.171  63.0  0.0
764   2.0  122.0  70.0  27.0    0.0  36.8  0.340  27.0  0.0
765   5.0  121.0  72.0  23.0  112.0  26.2  0.245  30.0  0.0
766   1.0  126.0  60.0   0.0    0.0  30.1  0.349  47.0  1.0
767   1.0   93.0  70.0  31.0    0.0  30.4  0.315  23.0  0.0

[768 rows x 9 columns]

In [ ]:
from sklearn import datasets as dt
from sklearn.linear_model import Perceptron
from sklearn.model_selection import train_test_split
from sklearn.metrics import accuracy_score
from sklearn.preprocessing import StandardScaler
import numpy as np

X = data.iloc[:, 0:8]
y = data.iloc[:,-1]
X_train, X_test, y_train, y_test = train_test_split(X, y, test_size=0.2,random_state=0)

standard = StandardScaler()
X_train_sc = standard.fit_transform(X_train)
X_test_sc = standard.transform(X_test)
# X_train_sc = X_train/255
# X_test_sc = X_test/255
model = Perceptron(max_iter=100, eta0=0.1, random_state=0)
model.fit(X_train_sc, y_train)
y_pred = model.predict(X_test_sc)

print(y_pred)
print(np.array(y_test))
print('độ chính xác khi scale: ', accuracy_score(y_test, y_pred))

[1. 1. 0. 1. 0. 0. 1. 1. 1. 1. 1. 1. 0. 0. 0. 0. 1. 0. 0. 0. 1. 1. 0. 0.
 0. 1. 0. 1. 0. 0. 0. 1. 0. 1. 0. 1. 1. 0. 1. 1. 1. 1. 0. 1. 1. 0. 0. 0.
 1. 1. 0. 0. 1. 1. 1. 0. 0. 1. 0. 0. 1. 1. 0. 1. 1. 1. 1. 0. 0. 0. 0. 0.
 0. 1. 1. 1. 0. 1. 0. 1. 1. 1. 1. 0. 0. 1. 0. 1. 1. 1. 0. 0. 0. 0. 1. 0.
 1. 1. 1. 0. 1. 0. 1. 0. 1. 0. 0. 1. 0. 1. 0. 1. 1. 1. 1. 1. 0. 1. 0. 1.
 1. 1. 1. 0. 0. 0. 1. 1. 0. 0. 1. 0. 0. 1. 0. 0. 0. 1. 1. 0. 0. 1. 0. 0.
 0. 0. 0. 0. 0. 1. 0. 1. 0. 0.]
[1. 0. 0. 1. 0. 0. 1. 1. 0. 0. 1. 1. 0. 0. 0. 0. 1. 0. 0. 0. 1. 1. 0. 0.
 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 1. 1. 0. 0. 0. 0. 0. 0. 1. 1. 0. 0. 1.
 1. 1. 0. 0. 1. 0. 0. 0. 0. 1. 1. 1. 1. 0. 0. 1. 1. 1. 1. 0. 0. 0. 0. 0.
 0. 0. 1. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 1. 0. 1. 0. 0. 0. 0. 0. 0. 0.
 1. 0. 1. 1. 0. 0. 0. 0. 0. 1. 0. 0. 0. 1. 0. 1. 1. 1. 1. 1. 0. 0. 0. 1.
 0. 0. 0. 0. 0. 0. 0. 1. 0. 0. 0. 0. 0. 1. 0. 1. 0. 1. 1. 0. 0. 0. 0. 0.
 1. 0. 0. 0. 0. 1. 0. 1. 0. 0.]
độ chính xác khi scale:  0.7077922077922078
